name: Deploy Extent Reports

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  actions: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests and generate reports
      run: mvn clean test

    - name: Debug directory
      run: ls -R

    - name: Deploy reports
      run: |
        if [ -d "./ExtentReports" ]; then
          cp ./ExtentReports/* /ExtentReportsDemo
        else
          echo "No reports to deploy"
        fi
